{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hexenbytes",
    "module": "demomodule",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "m4sp3shlsbbmxpnzrlvhukfw5e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "demomodule-1.0.1.aar",
          "url": "demomodule-1.0.1.aar",
          "size": 33775,
          "sha512": "5247cc184e3c9f40fd8a8d8a34461ab940ebe77df111e93fdbf69f5f66bd0dcf5e7286a9e345b03a0a9c97b53f23c5f1369885c5b2dfdf4be15a2aceb05e2c7e",
          "sha256": "d02884287e736ac8ae1b348547d514ea67a0428fa00850a4d8ea3ecb3ea4d839",
          "sha1": "6cbb2e44864bb29ed7ed4b88b71fe469722641c0",
          "md5": "91b9b68664edcd02da7bc9be872aa563"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "demomodule-1.0.1.aar",
          "url": "demomodule-1.0.1.aar",
          "size": 33775,
          "sha512": "5247cc184e3c9f40fd8a8d8a34461ab940ebe77df111e93fdbf69f5f66bd0dcf5e7286a9e345b03a0a9c97b53f23c5f1369885c5b2dfdf4be15a2aceb05e2c7e",
          "sha256": "d02884287e736ac8ae1b348547d514ea67a0428fa00850a4d8ea3ecb3ea4d839",
          "sha1": "6cbb2e44864bb29ed7ed4b88b71fe469722641c0",
          "md5": "91b9b68664edcd02da7bc9be872aa563"
        }
      ]
    }
  ]
}
